config/routes.rb
resources :timelog_tracker, :only => [] do
  collection do
    get :autocomplete_issues
    post :start
    match :update, via: :patch
    post :cancel
    post :commit
  end
end

app/models/tracked_time_entry.rb
class TrackedTimeEntry < ActiveRecord::Base
  include Redmine::SafeAttributes
  
  unloadable

  belongs_to :issue
  belongs_to :user
  belongs_to :activity, :class_name => 'TimeEntryActivity', :foreign_key => 'activity_id'

  validates_presence_of :user_id

  safe_attributes 'issue_id', 'activity_id'
end

app/controllers/timelog_tracker_controller.rb
class TimelogTrackerController < ApplicationController
  unloadable

  before_filter :find_project, only: :autocomplete_issues

  before_filter do
    User.current.allowed_to_globally? :log_time, {}
  end

  def autocomplete_issues
    @issues = []
    q = (params[:q] || params[:term]).to_s.strip
    if q.present?
      scope = (@project.nil? ? Issue : @project.issues).visible
      if q.match(/\A#?(\d+)\z/)
        @issues << scope.find_by_id($1.to_i)
      end
      @issues += scope.where("LOWER(#{Issue.table_name}.subject) LIKE LOWER(?)", "%#{q}%").order("#{Issue.table_name}.id DESC").limit(10).all
      @issues.compact!
    end

    json_data = @issues.map do |issue|
      {
        id: issue.id,
        label: "[#{issue.project.name}] #{issue.tracker} ##{issue.id}: #{issue.subject.to_s.truncate(60)}",
        value: issue.id,
        project: ({
          id: issue.project.id,
          activities: issue.project.activities.map do |activity|
            {
              id: activity.id,
              name: activity.name,
            }
          end
        } if issue.project)
      }
    end

    render :json => json_data
  end

  def cancel
    if !current_tracked_time_entry || current_tracked_time_entry.destroy
      head :ok      
    else
      head 500
    end
  end

  def start
    entry = TrackedTimeEntry.new
    entry.user = User.current
    entry.safe_attributes = params[:timelog_tracker]

    if current_tracked_time_entry
      render status: :bad_request, json: {
        error_code: "tracked_time_entry_already_exists"
      }
    elsif entry.save
      render json: entry
    else
      render status: :bad_request, json: {
        error_code: "save_failed",
        errors: entry.errors.full_messages
      }
    end
  end

  def update
    if current_tracked_time_entry
      current_tracked_time_entry.safe_attributes = params[:timelog_tracker] if params[:timelog_tracker]
      current_tracked_time_entry.save

      render json: current_tracked_time_entry
    else
      render status: :bad_request, json: {
        error_code: "tracked_time_entry_doesnt_exist"
      }
    end
  end

  def commit
    if current_tracked_time_entry
      current_tracked_time_entry.safe_attributes = params[:timelog_tracker] if params[:timelog_tracker]

      time_entry = TimeEntry.new
      time_entry.user = current_tracked_time_entry.user
      time_entry.activity = current_tracked_time_entry.activity
      time_entry.issue = current_tracked_time_entry.issue
      time_entry.spent_on = current_tracked_time_entry.created_at.to_date
      time_entry.hours = ((Time.now - current_tracked_time_entry.created_at) / 1.hour).round(2)

      if time_entry.transaction { time_entry.save && current_tracked_time_entry.destroy }
        render json: time_entry
      else
        render status: :bad_request, json: {
          error_code: "save_failed",
          errors: time_entry.errors.full_messages
        }
      end
    else
      render status: :bad_request, json: {
        error_code: "tracked_time_entry_doesnt_exist"
      }
    end
  end

    private

    def current_tracked_time_entry
      @current_tracked_time_entry ||= TrackedTimeEntry.find_by_user_id(User.current.id)
    end

    def find_project
      if params[:project_id].present?
        @project = Project.find(params[:project_id])
      end
    rescue ActiveRecord::RecordNotFound
      render_404
    end
end

app/views/application/_timelog_tracker.html.erb
<div id="timelog_tracker">
  <%= form_tag(:method => :post) do |f| %>
    <label for='timelog_tracker_issue_id'>
      <%= t(:tracker, scope: :timelog_tracker) %>:
    </label>
    <%= text_field_tag "timelog_tracker[issue_id]", nil, :size => 6, :required => true %>

    <%= select_tag "timelog_tracker[activity_id]", options_for_select(activity_collection_for_timelog_tracker_select_options), :required => true %>
    <%= submit_tag t(:start, scope: :timelog_tracker), :class => "button start-button" %>
    <%= submit_tag t(:cancel, scope: :timelog_tracker), :class => "button cancel-button", :type => :reset %>
    <%= submit_tag t(:commit, scope: :timelog_tracker), :class => "button commit-button" %>
    <%= submit_tag t(:commit_and_edit, scope: :timelog_tracker), :class => "button commit-and-edit-button" %>
  <% end %>

  <div class="subtitle">
    <% issue = current_tracked_time_entry.issue if current_tracked_time_entry %>
    <span id="timelog_tracker_issue_name"><%= ("[#{issue.project.name}] #{issue.tracker} ##{issue.id}: #{issue.subject.to_s.truncate(60)}") if issue %></span>

    <span id="timelog_tracker_time"></span>
  </div>
</div>

<%= javascript_include_tag 'jquery.ba-throttle-debounce.min.js', plugin: 'espeo_timelog_tracker' %>
<%= javascript_include_tag 'timelog_tracker', plugin: 'espeo_timelog_tracker' %>
<%= stylesheet_link_tag 'timelog_tracker', plugin: 'espeo_timelog_tracker' %>

<%= javascript_tag do %>
  observeAutocompleteField('timelog_tracker_issue_id', '<%= escape_javascript autocomplete_issues_timelog_tracker_index_path(:project_id => @project) %>', {
    select: function(event, ui) {
      $(this).change();
      $('#timelog_tracker_issue_name').text(ui.item.label);
      if (ui.item.project && ui.item.project.activities.length) {
        timelogTracker.setActivities(ui.item.project.activities);
      }
    }
  });

  jQuery(document).ready(function(){
    timelogTracker._setCurrentTrackedTimeEntry((<%= current_tracked_time_entry.to_json.html_safe %> || {}).tracked_time_entry);
  });
<% end %>